name: CD
on:
  release:
    types:
      - published

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}

jobs:
  cloudrun:
    name: "Google Cloud Run"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Auth
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.RUN_PROJECT }}
      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker
      # Build the Docker image
      - name: Build
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/benno-lin-web" .
      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push "gcr.io/$PROJECT_ID/benno-lin-web"
      - name: Deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          image: gcr.io/${{ secrets.RUN_PROJECT }}/benno-lin-web
          service: benno-lin-web
